require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/seeds.rb
    - node_modules/**/*

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
  Exclude:
    - config/routes.rb

Layout/LineLength:
  Exclude:
    - config/**/*.rb

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - config/environments/development.rb
    - lib/tasks/*.rake
    - spec/**/*.rb

Rails/FilePath:
  Exclude:
  - config/environments/development.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
