require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/seeds.rb
    - node_modules/**/*

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
  Exclude:
    - config/routes.rb

Layout/LineLength:
  Exclude:
    - app/models/user.rb
    - config/**/*.rb
    - lib/tasks/sample_data.rake

Lint/EmptyBlock:
  Exclude:
    - app/controllers/comments_controller.rb
    - app/controllers/photo_posts_controller.rb
    - app/controllers/text_posts_controller.rb

Metrics/AbcSize:
  Exclude:
  - app/controllers/comments_controller.rb
  - app/models/user.rb
  - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - config/environments/*
    - lib/tasks/*.rake
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
  - app/controllers/comments_controller.rb
  - app/models/user.rb
  - db/migrate/*.rb
  - spec/support/oauth.rb

Rails/BulkChangeTable:
  Exclude:
  - db/migrate/*.rb

Rails/CreateTableWithTimestamps:
  Exclude:
  - db/migrate/*.rb

Rails/FilePath:
  Exclude:
  - config/environments/development.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/GuardClause:
  Exclude:
    - app/controllers/users/devise_controller.rb
